version: "3"

services:
  db:
    build:
      context: ./db
      dockerfile: Dockerfile
      args:
        TARGETOS: linux
        TARGETARCH: amd64
        VERSION: 0.8.0
    ports:
      - "2040:8090"
    volumes:
      - ./db/pb_data:/pb/pb_data
    networks:
      - local

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    volumes:
      - ./client:/app
    ports:
      - "2041:3000"
    depends_on:
      - db
    networks:
      - local

  webserver:
    image: nginx:mainline-alpine
    container_name: webserver
    restart: unless-stopped
    ports:
      - "4030:80"
      - "80:4031"
    volumes:
      - ./nginx-conf:/etc/nginx/conf.d
    depends_on:
      - client
    networks:
      - local

networks:
  local:
    driver: bridge
