version: "3"

services:
  db:
    build:
      context: ./db
      dockerfile: Dockerfile

      args:
        TARGETOS: linux
        TARGETARCH: amd64
        VERSION: 0.8.0
    ports:
      - "2040:8090"
    volumes:
      - ./db/pb_data:/pb_data
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    volumes:
      - ./client/build:/build
    ports:
      - "2041:3000"
    links:
      - "db:database"
    depends_on:
      - db
    environment:
      - VITE_DB_PATH=db
